### PR TITLE
Add shell script linter, fixed warnings

### PR DESCRIPTION
**Pull request by SWW13**
Added [shellcheck](https://github.com/koalaman/shellcheck) linter for shell scripts.
Fixed all shellcheck warnings.

### CODE REVIEW

**Comment by mmaechtel** [comment]
Please test with workstation environment for bsys students. We have to double check what kind of dependencies we need on:
- Workstations in Lab
- Unix Env at home

**Comment by SWW13** [comment]
Dependencies:
- `find` was already a dependency and should be available all common linux distributions
- `read` is built in in `bash`
- `shellcheck` is most likely not available and therefore not part of `ci/run-all.sh`

Tested with:
- docker image ubuntu:yakkety
- OS X 10.12.3 (works - except existing issues with BSD `wc -L`) 

**TODO**:
- Test with Workstations in Lab

**Comment by mmaechtel** [comment]
we use a different linux environment in the labs: `nix-shell`. 

Therefore I created a new issue in a different repo and sent invitations to Tutors to discuss how to add/change software components

**Comment by mmaechtel** [comment]
Tested with Travis-CI ?

**Comment by SWW13** [comment]
Travis-CI works, except errors for unfinished tasks:
https://travis-ci.org/SWW13/bsys-ss17-homework/builds/211798041

**Comment by mmaechtel** [comment]
ok, after I know how to extend software packages 'the right way' (@steveeJ ) inside nix-shell i merge this PR

**Comment by mmaechtel** [comment]
my mix of german and english comments is still not great, but this will change when I have more time for it ...

**Comment by SWW13** [comment]
067e3c3570380da26a109e533e69b9075b05ec65 enables output of printfmt for students, this should be a great improvment:

```
=== Searching for files with rustfmt warnings ========================
Diff in ./hw0/task1/src/main.rs at line 5:
     multiple_hello("Ferris", 2);⏎
 }⏎
 pub fn multiple_hello(name: &str, n: i32) {⏎
-let mut i = 0;⏎
-while i<n{⏎
-    println!("Hello, {}!", name);⏎
-    i += 1;⏎
-}⏎
+    let mut i = 0;⏎
+    while i < n {⏎
+        println!("Hello, {}!", name);⏎
+        i += 1;⏎
+    }⏎
 }⏎
```

**Comment by mmaechtel** [comment]
yeah i saw this already, good idea!

**Comment by mmaechtel** [comment]
How do we deploy all the new scripts to the students?

**Comment by mmaechtel** [comment]
running:
```
./ci/run-all.sh

=== Searching for lines with trailing whitespace... ===================
find: unknown predicate `-E'
=== None found! :-)

=== Searching for files without trailing newline... ===================
find: unknown predicate `-E'
=== None found! :-)

=== Searching for files with wrong line endings ===================
find: unknown predicate `-E'
=== None found! :-)

=== Searching for files with tab chars ===================
find: unknown predicate `-E'
=== None found! :-)

=== Searching for files with too long lines... ========================
find: unknown predicate `-E'
=== None found! :-)

=== Searching for files with rustfmt warnings ========================
find: unknown predicate `-E'
=== None found! :-)

=== Aktuelles Aufgabenblatt ist in Ordner ./hw0

=== Teste Lösung von Aufgabe in ./hw0/task1
=== Cargo-Manifest gefunden in './hw0/task1/Cargo.toml' -> Cargo-Modus
   Compiling task1 v0.1.0 (file:///home/maechtel/bsys-ss17-homework/hw0/task1)
    Finished debug [unoptimized + debuginfo] target(s) in 1.36 secs
     Running hw0/task1/target/debug/deps/task1-33e4e09b40a9f9d8

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```
on a bsys workstation with installed shellcheck. Why reports find -E ?

**Comment by SWW13** [comment]
I'm working on that, find works different for BSD and Linux.

**Comment by mmaechtel** [comment]
Yep! find works. Great !!

**Comment by SWW13** [comment]
Everything should work now.

Tested on OS X and BSYS container.

**Comment by SWW13** [comment]
About the distribution: We could rebase/cherry-pick these commits into each group repository and then each group can simply merge/rebase the update.

**Comment by mmaechtel** [comment]
so we could do this with acceptance of the PR for hw0-t2 ?

**Comment by SWW13** [comment]
Sounds good, after hw0 they should be able to merge upstream changes.

**Pull request merged**
